name: Deploy Organization README to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site Repo
        uses: actions/checkout@v4

      - name: Fetch Organization README
        run: |
          curl -L https://raw.githubusercontent.com/Cyber-Threat-Hunting-Playground/.github/main/profile/README.md -o index.md
          # Adding Jekyll Front Matter
          echo -e "---\nlayout: default\ntitle: Home\n---\n$(cat index.md)" > index.md

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
